//# sourceMappingURL=bootstrap-3.4.1-mf.js.map
/*
 Bootstrap v3.4.1 (https://getbootstrap.com/)
 Copyright 2011-2019 Twitter, Inc.
 Licensed under the MIT license
*/
var process=process||{env:{NODE_ENV:"development"}};if("undefined"===typeof jQuery)throw Error("Bootstrap's JavaScript requires jQuery");+function(a){a=a.fn.jquery.split(" ")[0].split(".");if(2>a[0]&&9>a[1]||1==a[0]&&9==a[1]&&1>a[2]||3<a[0])throw Error("Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 4");}(jQuery);
+function(a){function n(){var h=document.createElement("bootstrap"),m={WebkitTransition:"webkitTransitionEnd",MozTransition:"transitionend",OTransition:"oTransitionEnd otransitionend",transition:"transitionend"},g;for(g in m)if(void 0!==h.style[g])return{end:m[g]};return!1}a.fn.emulateTransitionEnd=function(h){var m=!1,g=this;a(this).one("bsTransitionEnd",function(){m=!0});setTimeout(function(){m||a(g).trigger(a.support.transition.end)},h);return this};a(function(){a.support.transition=n();a.support.transition&&
(a.event.special.bsTransitionEnd={bindType:a.support.transition.end,delegateType:a.support.transition.end,handle:function(h){if(a(h.target).is(this))return h.handleObj.handler.apply(this,arguments)}})})}(jQuery);
+function(a){var n=function(m){a(m).on("click",'[data-dismiss="alert"]',this.close)};n.VERSION="3.4.1";n.TRANSITION_DURATION=150;n.prototype.close=function(m){function g(){c.detach().trigger("closed.bs.alert").remove()}var b=a(this),d=b.attr("data-target");d||(d=(d=b.attr("href"))&&d.replace(/.*(?=#[^\s]*$)/,""));d="#"===d?[]:d;var c=a(document).find(d);m&&m.preventDefault();c.length||(c=b.closest(".alert"));c.trigger(m=a.Event("close.bs.alert"));m.isDefaultPrevented()||(c.removeClass("in"),a.support.transition&&
c.hasClass("fade")?c.one("bsTransitionEnd",g).emulateTransitionEnd(n.TRANSITION_DURATION):g())};var h=a.fn.alert;a.fn.alert=function(m){return this.each(function(){var g=a(this),b=g.data("bs.alert");b||g.data("bs.alert",b=new n(this));"string"==typeof m&&b[m].call(g)})};a.fn.alert.Constructor=n;a.fn.alert.noConflict=function(){a.fn.alert=h;return this};a(document).on("click.bs.alert.data-api",'[data-dismiss="alert"]',n.prototype.close)}(jQuery);
+function(a){function n(g){return this.each(function(){var b=a(this),d=b.data("bs.button"),c="object"==typeof g&&g;d||b.data("bs.button",d=new h(this,c));"toggle"==g?d.toggle():g&&d.setState(g)})}var h=function(g,b){this.$element=a(g);this.options=a.extend({},h.DEFAULTS,b);this.isLoading=!1};h.VERSION="3.4.1";h.DEFAULTS={loadingText:"loading..."};h.prototype.setState=function(g){var b=this.$element,d=b.is("input")?"val":"html",c=b.data();g+="Text";null==c.resetText&&b.data("resetText",b[d]());setTimeout(a.proxy(function(){b[d](null==
c[g]?this.options[g]:c[g]);"loadingText"==g?(this.isLoading=!0,b.addClass("disabled").attr("disabled","disabled").prop("disabled",!0)):this.isLoading&&(this.isLoading=!1,b.removeClass("disabled").removeAttr("disabled").prop("disabled",!1))},this),0)};h.prototype.toggle=function(){var g=!0,b=this.$element.closest('[data-toggle="buttons"]');if(b.length){var d=this.$element.find("input");"radio"==d.prop("type")?(d.prop("checked")&&(g=!1),b.find(".active").removeClass("active"),this.$element.addClass("active")):
"checkbox"==d.prop("type")&&(d.prop("checked")!==this.$element.hasClass("active")&&(g=!1),this.$element.toggleClass("active"));d.prop("checked",this.$element.hasClass("active"));g&&d.trigger("change")}else this.$element.attr("aria-pressed",!this.$element.hasClass("active")),this.$element.toggleClass("active")};var m=a.fn.button;a.fn.button=n;a.fn.button.Constructor=h;a.fn.button.noConflict=function(){a.fn.button=m;return this};a(document).on("click.bs.button.data-api",'[data-toggle^="button"]',function(g){var b=
a(g.target).closest(".btn");n.call(b,"toggle");a(g.target).is('input[type="radio"], input[type="checkbox"]')||(g.preventDefault(),b.is("input,button")?b.trigger("focus"):b.find("input:visible,button:visible").first().trigger("focus"))}).on("focus.bs.button.data-api blur.bs.button.data-api",'[data-toggle^="button"]',function(g){a(g.target).closest(".btn").toggleClass("focus",/^focus(in)?$/.test(g.type))})}(jQuery);
+function(a){function n(b){return this.each(function(){var d=a(this),c=d.data("bs.carousel"),k=a.extend({},h.DEFAULTS,d.data(),"object"==typeof b&&b),e="string"==typeof b?b:k.slide;c||d.data("bs.carousel",c=new h(this,k));if("number"==typeof b)c.to(b);else if(e)c[e]();else k.interval&&c.pause().cycle()})}var h=function(b,d){this.$element=a(b);this.$indicators=this.$element.find(".carousel-indicators");this.options=d;this.$items=this.$active=this.interval=this.sliding=this.paused=null;this.options.keyboard&&
this.$element.on("keydown.bs.carousel",a.proxy(this.keydown,this));"hover"!=this.options.pause||"ontouchstart"in document.documentElement||this.$element.on("mouseenter.bs.carousel",a.proxy(this.pause,this)).on("mouseleave.bs.carousel",a.proxy(this.cycle,this))};h.VERSION="3.4.1";h.TRANSITION_DURATION=600;h.DEFAULTS={interval:5E3,pause:"hover",wrap:!0,keyboard:!0};h.prototype.keydown=function(b){if(!/input|textarea/i.test(b.target.tagName)){switch(b.which){case 37:this.prev();break;case 39:this.next();
break;default:return}b.preventDefault()}};h.prototype.cycle=function(b){b||(this.paused=!1);this.interval&&clearInterval(this.interval);this.options.interval&&!this.paused&&(this.interval=setInterval(a.proxy(this.next,this),this.options.interval));return this};h.prototype.getItemIndex=function(b){this.$items=b.parent().children(".item");return this.$items.index(b||this.$active)};h.prototype.getItemForDirection=function(b,d){var c=this.getItemIndex(d);return("prev"==b&&0===c||"next"==b&&c==this.$items.length-
1)&&!this.options.wrap?d:this.$items.eq((c+("prev"==b?-1:1))%this.$items.length)};h.prototype.to=function(b){var d=this,c=this.getItemIndex(this.$active=this.$element.find(".item.active"));if(!(b>this.$items.length-1||0>b))return this.sliding?this.$element.one("slid.bs.carousel",function(){d.to(b)}):c==b?this.pause().cycle():this.slide(b>c?"next":"prev",this.$items.eq(b))};h.prototype.pause=function(b){b||(this.paused=!0);this.$element.find(".next, .prev").length&&a.support.transition&&(this.$element.trigger(a.support.transition.end),
this.cycle(!0));this.interval=clearInterval(this.interval);return this};h.prototype.next=function(){if(!this.sliding)return this.slide("next")};h.prototype.prev=function(){if(!this.sliding)return this.slide("prev")};h.prototype.slide=function(b,d){var c=this.$element.find(".item.active"),k=d||this.getItemForDirection(b,c);d=this.interval;var e="next"==b?"left":"right",f=this;if(k.hasClass("active"))return this.sliding=!1;var l=k[0],p=a.Event("slide.bs.carousel",{relatedTarget:l,direction:e});this.$element.trigger(p);
if(!p.isDefaultPrevented()){this.sliding=!0;d&&this.pause();this.$indicators.length&&(this.$indicators.find(".active").removeClass("active"),(p=a(this.$indicators.children()[this.getItemIndex(k)]))&&p.addClass("active"));var r=a.Event("slid.bs.carousel",{relatedTarget:l,direction:e});a.support.transition&&this.$element.hasClass("slide")?(k.addClass(b),"object"===typeof k&&k.length&&k[0].offsetWidth,c.addClass(e),k.addClass(e),c.one("bsTransitionEnd",function(){k.removeClass([b,e].join(" ")).addClass("active");
c.removeClass(["active",e].join(" "));f.sliding=!1;setTimeout(function(){f.$element.trigger(r)},0)}).emulateTransitionEnd(h.TRANSITION_DURATION)):(c.removeClass("active"),k.addClass("active"),this.sliding=!1,this.$element.trigger(r));d&&this.cycle();return this}};var m=a.fn.carousel;a.fn.carousel=n;a.fn.carousel.Constructor=h;a.fn.carousel.noConflict=function(){a.fn.carousel=m;return this};var g=function(b){var d=a(this),c=d.attr("href");c&&(c=c.replace(/.*(?=#[^\s]+$)/,""));c=d.attr("data-target")||
c;c=a(document).find(c);if(c.hasClass("carousel")){var k=a.extend({},c.data(),d.data());if(d=d.attr("data-slide-to"))k.interval=!1;n.call(c,k);d&&c.data("bs.carousel").to(d);b.preventDefault()}};a(document).on("click.bs.carousel.data-api","[data-slide]",g).on("click.bs.carousel.data-api","[data-slide-to]",g);a(window).on("load",function(){a('[data-ride="carousel"]').each(function(){var b=a(this);n.call(b,b.data())})})}(jQuery);
+function(a){function n(b){var d;b=b.attr("data-target")||(d=b.attr("href"))&&d.replace(/.*(?=#[^\s]+$)/,"");return a(document).find(b)}function h(b){return this.each(function(){var d=a(this),c=d.data("bs.collapse"),k=a.extend({},m.DEFAULTS,d.data(),"object"==typeof b&&b);!c&&k.toggle&&/show|hide/.test(b)&&(k.toggle=!1);c||d.data("bs.collapse",c=new m(this,k));if("string"==typeof b)c[b]()})}var m=function(b,d){this.$element=a(b);this.options=a.extend({},m.DEFAULTS,d);this.$trigger=a('[data-toggle="collapse"][href="#'+
b.id+'"],[data-toggle="collapse"][data-target="#'+b.id+'"]');this.transitioning=null;this.options.parent?this.$parent=this.getParent():this.addAriaAndCollapsedClass(this.$element,this.$trigger);this.options.toggle&&this.toggle()};m.VERSION="3.4.1";m.TRANSITION_DURATION=350;m.DEFAULTS={toggle:!0};m.prototype.dimension=function(){return this.$element.hasClass("width")?"width":"height"};m.prototype.show=function(){if(!this.transitioning&&!this.$element.hasClass("in")){var b,d=this.$parent&&this.$parent.children(".panel").children(".in, .collapsing");
if(d&&d.length&&(b=d.data("bs.collapse"))&&b.transitioning)return;var c=a.Event("show.bs.collapse");this.$element.trigger(c);if(!c.isDefaultPrevented()){d&&d.length&&(h.call(d,"hide"),b||d.data("bs.collapse",null));var k=this.dimension();this.$element.removeClass("collapse").addClass("collapsing")[k](0).attr("aria-expanded",!0);this.$trigger.removeClass("collapsed").attr("aria-expanded",!0);this.transitioning=1;b=function(){this.$element.removeClass("collapsing").addClass("collapse in")[k]("");this.transitioning=
0;this.$element.trigger("shown.bs.collapse")};if(!a.support.transition)return b.call(this);d=a.camelCase(["scroll",k].join("-"));this.$element.one("bsTransitionEnd",a.proxy(b,this)).emulateTransitionEnd(m.TRANSITION_DURATION)[k](this.$element[0][d])}}};m.prototype.hide=function(){if(!this.transitioning&&this.$element.hasClass("in")){var b=a.Event("hide.bs.collapse");this.$element.trigger(b);if(!b.isDefaultPrevented()){b=this.dimension();this.$element[b](this.$element[b]())[0].offsetHeight;this.$element.addClass("collapsing").removeClass("collapse in").attr("aria-expanded",
!1);this.$trigger.addClass("collapsed").attr("aria-expanded",!1);this.transitioning=1;var d=function(){this.transitioning=0;this.$element.removeClass("collapsing").addClass("collapse").trigger("hidden.bs.collapse")};if(!a.support.transition)return d.call(this);this.$element[b](0).one("bsTransitionEnd",a.proxy(d,this)).emulateTransitionEnd(m.TRANSITION_DURATION)}}};m.prototype.toggle=function(){this[this.$element.hasClass("in")?"hide":"show"]()};m.prototype.getParent=function(){return a(document).find(this.options.parent).find('[data-toggle="collapse"][data-parent="'+
this.options.parent+'"]').each(a.proxy(function(b,d){b=a(d);this.addAriaAndCollapsedClass(n(b),b)},this)).end()};m.prototype.addAriaAndCollapsedClass=function(b,d){var c=b.hasClass("in");b.attr("aria-expanded",c);d.toggleClass("collapsed",!c).attr("aria-expanded",c)};var g=a.fn.collapse;a.fn.collapse=h;a.fn.collapse.Constructor=m;a.fn.collapse.noConflict=function(){a.fn.collapse=g;return this};a(document).on("click.bs.collapse.data-api",'[data-toggle="collapse"]',function(b){var d=a(this);d.attr("data-target")||
b.preventDefault();b=n(d);d=b.data("bs.collapse")?"toggle":d.data();h.call(b,d)})}(jQuery);
+function(a){function n(b){var d=b.attr("data-target");d||(d=(d=b.attr("href"))&&/#[A-Za-z]/.test(d)&&d.replace(/.*(?=#[^\s]*$)/,""));return(d="#"!==d?a(document).find(d):null)&&d.length?d:b.parent()}function h(b){b&&3===b.which||(a(".dropdown-backdrop").remove(),a('[data-toggle="dropdown"]').each(function(){var d=a(this),c=n(d),k={relatedTarget:this};!c.hasClass("open")||b&&"click"==b.type&&/input|textarea/i.test(b.target.tagName)&&a.contains(c[0],b.target)||(c.trigger(b=a.Event("hide.bs.dropdown",
k)),b.isDefaultPrevented()||(d.attr("aria-expanded","false"),c.removeClass("open").trigger(a.Event("hidden.bs.dropdown",k))))}))}var m=function(b){a(b).on("click.bs.dropdown",this.toggle)};m.VERSION="3.4.1";m.prototype.toggle=function(b){var d=a(this);if(!d.is(".disabled, :disabled")){var c=n(d);b=c.hasClass("open");h();if(!b){if("ontouchstart"in document.documentElement&&!c.closest(".navbar-nav").length)a(document.createElement("div")).addClass("dropdown-backdrop").insertAfter(a(this)).on("click",
h);var k={relatedTarget:this};c.trigger(b=a.Event("show.bs.dropdown",k));if(b.isDefaultPrevented())return;d.trigger("focus").attr("aria-expanded","true");c.toggleClass("open").trigger(a.Event("shown.bs.dropdown",k))}return!1}};m.prototype.keydown=function(b){if(/(38|40|27|32)/.test(b.which)&&!/input|textarea/i.test(b.target.tagName)){var d=a(this);b.preventDefault();b.stopPropagation();if(!d.is(".disabled, :disabled")){var c=n(d),k=c.hasClass("open");if(!k&&27!=b.which||k&&27==b.which)return 27==
b.which&&c.find('[data-toggle="dropdown"]').trigger("focus"),d.trigger("click");d=c.find(".dropdown-menu li:not(.disabled):visible a");d.length&&(c=d.index(b.target),38==b.which&&0<c&&c--,40==b.which&&c<d.length-1&&c++,~c||(c=0),d.eq(c).trigger("focus"))}}};var g=a.fn.dropdown;a.fn.dropdown=function(b){return this.each(function(){var d=a(this),c=d.data("bs.dropdown");c||d.data("bs.dropdown",c=new m(this));"string"==typeof b&&c[b].call(d)})};a.fn.dropdown.Constructor=m;a.fn.dropdown.noConflict=function(){a.fn.dropdown=
g;return this};a(document).on("click.bs.dropdown.data-api",h).on("click.bs.dropdown.data-api",".dropdown form",function(b){b.stopPropagation()}).on("click.bs.dropdown.data-api",'[data-toggle="dropdown"]',m.prototype.toggle).on("keydown.bs.dropdown.data-api",'[data-toggle="dropdown"]',m.prototype.keydown).on("keydown.bs.dropdown.data-api",".dropdown-menu",m.prototype.keydown)}(jQuery);
+function(a){function n(g,b){return this.each(function(){var d=a(this),c=d.data("bs.modal"),k=a.extend({},h.DEFAULTS,d.data(),"object"==typeof g&&g);c||d.data("bs.modal",c=new h(this,k));if("string"==typeof g)c[g](b);else k.show&&c.show(b)})}var h=function(g,b){this.options=b;this.$body=a(document.body);this.$element=a(g);this.$dialog=this.$element.find(".modal-dialog");this.originalBodyPad=this.isShown=this.$backdrop=null;this.scrollbarWidth=0;this.ignoreBackdropClick=!1;this.fixedContent=".navbar-fixed-top, .navbar-fixed-bottom";
this.options.remote&&this.$element.find(".modal-content").load(this.options.remote,a.proxy(function(){this.$element.trigger("loaded.bs.modal")},this))};h.VERSION="3.4.1";h.TRANSITION_DURATION=300;h.BACKDROP_TRANSITION_DURATION=150;h.DEFAULTS={backdrop:!0,keyboard:!0,show:!0};h.prototype.toggle=function(g){return this.isShown?this.hide():this.show(g)};h.prototype.show=function(g){var b=this,d=a.Event("show.bs.modal",{relatedTarget:g});this.$element.trigger(d);this.isShown||d.isDefaultPrevented()||
(this.isShown=!0,this.checkScrollbar(),this.setScrollbar(),this.$body.addClass("modal-open"),this.escape(),this.resize(),this.$element.on("click.dismiss.bs.modal",'[data-dismiss="modal"]',a.proxy(this.hide,this)),this.$dialog.on("mousedown.dismiss.bs.modal",function(){b.$element.one("mouseup.dismiss.bs.modal",function(c){a(c.target).is(b.$element)&&(b.ignoreBackdropClick=!0)})}),this.backdrop(function(){var c=a.support.transition&&b.$element.hasClass("fade");b.$element.parent().length||b.$element.appendTo(b.$body);
b.$element.show().scrollTop(0);b.adjustDialog();c&&b.$element[0].offsetWidth;b.$element.addClass("in");b.enforceFocus();var k=a.Event("shown.bs.modal",{relatedTarget:g});c?b.$dialog.one("bsTransitionEnd",function(){b.$element.trigger("focus").trigger(k)}).emulateTransitionEnd(h.TRANSITION_DURATION):b.$element.trigger("focus").trigger(k)}))};h.prototype.hide=function(g){g&&g.preventDefault();g=a.Event("hide.bs.modal");this.$element.trigger(g);this.isShown&&!g.isDefaultPrevented()&&(this.isShown=!1,
this.escape(),this.resize(),a(document).off("focusin.bs.modal"),this.$element.removeClass("in").off("click.dismiss.bs.modal").off("mouseup.dismiss.bs.modal"),this.$dialog.off("mousedown.dismiss.bs.modal"),a.support.transition&&this.$element.hasClass("fade")?this.$element.one("bsTransitionEnd",a.proxy(this.hideModal,this)).emulateTransitionEnd(h.TRANSITION_DURATION):this.hideModal())};h.prototype.enforceFocus=function(){a(document).off("focusin.bs.modal").on("focusin.bs.modal",a.proxy(function(g){document===
g.target||this.$element[0]===g.target||this.$element.has(g.target).length||this.$element.trigger("focus")},this))};h.prototype.escape=function(){if(this.isShown&&this.options.keyboard)this.$element.on("keydown.dismiss.bs.modal",a.proxy(function(g){27==g.which&&this.hide()},this));else this.isShown||this.$element.off("keydown.dismiss.bs.modal")};h.prototype.resize=function(){if(this.isShown)a(window).on("resize.bs.modal",a.proxy(this.handleUpdate,this));else a(window).off("resize.bs.modal")};h.prototype.hideModal=
function(){var g=this;this.$element.hide();this.backdrop(function(){g.$body.removeClass("modal-open");g.resetAdjustments();g.resetScrollbar();g.$element.trigger("hidden.bs.modal")})};h.prototype.removeBackdrop=function(){this.$backdrop&&this.$backdrop.remove();this.$backdrop=null};h.prototype.backdrop=function(g){var b=this,d=this.$element.hasClass("fade")?"fade":"";if(this.isShown&&this.options.backdrop){var c=a.support.transition&&d;this.$backdrop=a(document.createElement("div")).addClass("modal-backdrop "+
d).appendTo(this.$body);this.$element.on("click.dismiss.bs.modal",a.proxy(function(k){this.ignoreBackdropClick?this.ignoreBackdropClick=!1:k.target===k.currentTarget&&("static"==this.options.backdrop?this.$element[0].focus():this.hide())},this));c&&this.$backdrop[0].offsetWidth;this.$backdrop.addClass("in");g&&(c?this.$backdrop.one("bsTransitionEnd",g).emulateTransitionEnd(h.BACKDROP_TRANSITION_DURATION):g())}else!this.isShown&&this.$backdrop?(this.$backdrop.removeClass("in"),d=function(){b.removeBackdrop();
g&&g()},a.support.transition&&this.$element.hasClass("fade")?this.$backdrop.one("bsTransitionEnd",d).emulateTransitionEnd(h.BACKDROP_TRANSITION_DURATION):d()):g&&g()};h.prototype.handleUpdate=function(){this.adjustDialog()};h.prototype.adjustDialog=function(){var g=this.$element[0].scrollHeight>document.documentElement.clientHeight;this.$element.css({paddingLeft:!this.bodyIsOverflowing&&g?this.scrollbarWidth:"",paddingRight:this.bodyIsOverflowing&&!g?this.scrollbarWidth:""})};h.prototype.resetAdjustments=
function(){this.$element.css({paddingLeft:"",paddingRight:""})};h.prototype.checkScrollbar=function(){var g=window.innerWidth;g||(g=document.documentElement.getBoundingClientRect(),g=g.right-Math.abs(g.left));this.bodyIsOverflowing=document.body.clientWidth<g;this.scrollbarWidth=this.measureScrollbar()};h.prototype.setScrollbar=function(){var g=parseInt(this.$body.css("padding-right")||0,10);this.originalBodyPad=document.body.style.paddingRight||"";var b=this.scrollbarWidth;this.bodyIsOverflowing&&
(this.$body.css("padding-right",g+b),a(this.fixedContent).each(function(d,c){d=c.style.paddingRight;var k=a(c).css("padding-right");a(c).data("padding-right",d).css("padding-right",parseFloat(k)+b+"px")}))};h.prototype.resetScrollbar=function(){this.$body.css("padding-right",this.originalBodyPad);a(this.fixedContent).each(function(g,b){g=a(b).data("padding-right");a(b).removeData("padding-right");b.style.paddingRight=g?g:""})};h.prototype.measureScrollbar=function(){var g=document.createElement("div");
g.className="modal-scrollbar-measure";this.$body.append(g);var b=g.offsetWidth-g.clientWidth;this.$body[0].removeChild(g);return b};var m=a.fn.modal;a.fn.modal=n;a.fn.modal.Constructor=h;a.fn.modal.noConflict=function(){a.fn.modal=m;return this};a(document).on("click.bs.modal.data-api",'[data-toggle="modal"]',function(g){var b=a(this),d=b.attr("href"),c=b.attr("data-target")||d&&d.replace(/.*(?=#[^\s]+$)/,""),k=a(document).find(c);d=k.data("bs.modal")?"toggle":a.extend({remote:!/#/.test(d)&&d},k.data(),
b.data());b.is("a")&&g.preventDefault();k.one("show.bs.modal",function(e){if(!e.isDefaultPrevented())k.one("hidden.bs.modal",function(){b.is(":visible")&&b.trigger("focus")})});n.call(k,d,this)})}(jQuery);
+function(a){function n(e,f){var l=e.nodeName.toLowerCase();if(-1!==a.inArray(l,f))return-1!==a.inArray(l,g)?!(!e.nodeValue.match(b)&&!e.nodeValue.match(d)):!0;e=a(f).filter(function(r,t){return t instanceof RegExp});f=0;for(var p=e.length;f<p;f++)if(l.match(e[f]))return!0;return!1}function h(e,f,l){if(0===e.length)return e;if(l&&"function"===typeof l)return l(e);if(!document.implementation||!document.implementation.createHTMLDocument)return e;l=document.implementation.createHTMLDocument("sanitization");
l.body.innerHTML=e;e=a.map(f,function(x,y){return y});for(var p=a(l.body).find("*"),r=0,t=p.length;r<t;r++){var q=p[r],u=q.nodeName.toLowerCase();if(-1===a.inArray(u,e))q.parentNode.removeChild(q);else{var v=a.map(q.attributes,function(x){return x});u=[].concat(f["*"]||[],f[u]||[]);for(var w=0,z=v.length;w<z;w++)n(v[w],u)||q.removeAttribute(v[w].nodeName)}}return l.body.innerHTML}var m=["sanitize","whiteList","sanitizeFn"],g="background cite href itemtype longdesc poster src xlink:href".split(" "),
b=/^(?:(?:https?|mailto|ftp|tel|file):|[^&:/?#]*(?:[/?#]|$))/gi,d=/^data:(?:image\/(?:bmp|gif|jpeg|jpg|png|tiff|webp)|video\/(?:mpeg|mp4|ogg|webm)|audio\/(?:mp3|oga|ogg|opus));base64,[a-z0-9+/]+=*$/i,c=function(e,f){this.inState=this.$element=this.hoverState=this.timeout=this.enabled=this.options=this.type=null;this.init("tooltip",e,f)};c.VERSION="3.4.1";c.TRANSITION_DURATION=150;c.DEFAULTS={animation:!0,placement:"top",selector:!1,template:'<div class="tooltip" role="tooltip"><div class="tooltip-arrow"></div><div class="tooltip-inner"></div></div>',
trigger:"hover focus",title:"",delay:0,html:!1,container:!1,viewport:{selector:"body",padding:0},sanitize:!0,sanitizeFn:null,whiteList:{"*":["class","dir","id","lang","role",/^aria-[\w-]*$/i],a:["target","href","title","rel"],area:[],b:[],br:[],col:[],code:[],div:[],em:[],hr:[],h1:[],h2:[],h3:[],h4:[],h5:[],h6:[],i:[],img:["src","alt","title","width","height"],li:[],ol:[],p:[],pre:[],s:[],small:[],span:[],sub:[],sup:[],strong:[],u:[],ul:[]}};c.prototype.init=function(e,f,l){this.enabled=!0;this.type=
e;this.$element=a(f);this.options=this.getOptions(l);this.$viewport=this.options.viewport&&a(document).find(a.isFunction(this.options.viewport)?this.options.viewport.call(this,this.$element):this.options.viewport.selector||this.options.viewport);this.inState={click:!1,hover:!1,focus:!1};if(this.$element[0]instanceof document.constructor&&!this.options.selector)throw Error("`selector` option must be specified when initializing "+this.type+" on the window.document object!");e=this.options.trigger.split(" ");
for(f=e.length;f--;)if(l=e[f],"click"==l)this.$element.on("click."+this.type,this.options.selector,a.proxy(this.toggle,this));else if("manual"!=l){var p="hover"==l?"mouseleave":"focusout";this.$element.on(("hover"==l?"mouseenter":"focusin")+"."+this.type,this.options.selector,a.proxy(this.enter,this));this.$element.on(p+"."+this.type,this.options.selector,a.proxy(this.leave,this))}this.options.selector?this._options=a.extend({},this.options,{trigger:"manual",selector:""}):this.fixTitle()};c.prototype.getDefaults=
function(){return c.DEFAULTS};c.prototype.getOptions=function(e){var f=this.$element.data(),l;for(l in f)f.hasOwnProperty(l)&&-1!==a.inArray(l,m)&&delete f[l];e=a.extend({},this.getDefaults(),f,e);e.delay&&"number"==typeof e.delay&&(e.delay={show:e.delay,hide:e.delay});e.sanitize&&(e.template=h(e.template,e.whiteList,e.sanitizeFn));return e};c.prototype.getDelegateOptions=function(){var e={},f=this.getDefaults();this._options&&a.each(this._options,function(l,p){f[l]!=p&&(e[l]=p)});return e};c.prototype.enter=
function(e){var f=e instanceof this.constructor?e:a(e.currentTarget).data("bs."+this.type);f||(f=new this.constructor(e.currentTarget,this.getDelegateOptions()),a(e.currentTarget).data("bs."+this.type,f));e instanceof a.Event&&(f.inState["focusin"==e.type?"focus":"hover"]=!0);if(f.tip().hasClass("in")||"in"==f.hoverState)f.hoverState="in";else{clearTimeout(f.timeout);f.hoverState="in";if(!f.options.delay||!f.options.delay.show)return f.show();f.timeout=setTimeout(function(){"in"==f.hoverState&&f.show()},
f.options.delay.show)}};c.prototype.isInStateTrue=function(){for(var e in this.inState)if(this.inState[e])return!0;return!1};c.prototype.leave=function(e){var f=e instanceof this.constructor?e:a(e.currentTarget).data("bs."+this.type);f||(f=new this.constructor(e.currentTarget,this.getDelegateOptions()),a(e.currentTarget).data("bs."+this.type,f));e instanceof a.Event&&(f.inState["focusout"==e.type?"focus":"hover"]=!1);if(!f.isInStateTrue()){clearTimeout(f.timeout);f.hoverState="out";if(!f.options.delay||
!f.options.delay.hide)return f.hide();f.timeout=setTimeout(function(){"out"==f.hoverState&&f.hide()},f.options.delay.hide)}};c.prototype.show=function(){var e=a.Event("show.bs."+this.type);if(this.hasContent()&&this.enabled){this.$element.trigger(e);var f=a.contains(this.$element[0].ownerDocument.documentElement,this.$element[0]);if(!e.isDefaultPrevented()&&f){var l=this;e=this.tip();f=this.getUID(this.type);this.setContent();e.attr("id",f);this.$element.attr("aria-describedby",f);this.options.animation&&
e.addClass("fade");f="function"==typeof this.options.placement?this.options.placement.call(this,e[0],this.$element[0]):this.options.placement;var p=/\s?auto?\s?/i,r=p.test(f);r&&(f=f.replace(p,"")||"top");e.detach().css({top:0,left:0,display:"block"}).addClass(f).data("bs."+this.type,this);this.options.container?e.appendTo(a(document).find(this.options.container)):e.insertAfter(this.$element);this.$element.trigger("inserted.bs."+this.type);p=this.getPosition();var t=e[0].offsetWidth,q=e[0].offsetHeight;
if(r){r=f;var u=this.getPosition(this.$viewport);f="bottom"==f&&p.bottom+q>u.bottom?"top":"top"==f&&p.top-q<u.top?"bottom":"right"==f&&p.right+t>u.width?"left":"left"==f&&p.left-t<u.left?"right":f;e.removeClass(r).addClass(f)}p=this.getCalculatedOffset(f,p,t,q);this.applyPlacement(p,f);f=function(){var v=l.hoverState;l.$element.trigger("shown.bs."+l.type);l.hoverState=null;"out"==v&&l.leave(l)};a.support.transition&&this.$tip.hasClass("fade")?e.one("bsTransitionEnd",f).emulateTransitionEnd(c.TRANSITION_DURATION):
f()}}};c.prototype.applyPlacement=function(e,f){var l=this.tip(),p=l[0].offsetWidth,r=l[0].offsetHeight,t=parseInt(l.css("margin-top"),10),q=parseInt(l.css("margin-left"),10);isNaN(t)&&(t=0);isNaN(q)&&(q=0);e.top+=t;e.left+=q;a.offset.setOffset(l[0],a.extend({using:function(v){l.css({top:Math.round(v.top),left:Math.round(v.left)})}},e),0);l.addClass("in");t=l[0].offsetWidth;q=l[0].offsetHeight;"top"==f&&q!=r&&(e.top=e.top+r-q);var u=this.getViewportAdjustedDelta(f,e,t,q);u.left?e.left+=u.left:e.top+=
u.top;p=(f=/top|bottom/.test(f))?2*u.left-p+t:2*u.top-r+q;r=f?"offsetWidth":"offsetHeight";l.offset(e);this.replaceArrow(p,l[0][r],f)};c.prototype.replaceArrow=function(e,f,l){this.arrow().css(l?"left":"top",50*(1-e/f)+"%").css(l?"top":"left","")};c.prototype.setContent=function(){var e=this.tip(),f=this.getTitle();this.options.html?(this.options.sanitize&&(f=h(f,this.options.whiteList,this.options.sanitizeFn)),e.find(".tooltip-inner").html(f)):e.find(".tooltip-inner").text(f);e.removeClass("fade in top bottom left right")};
c.prototype.hide=function(e){function f(){"in"!=l.hoverState&&p.detach();l.$element&&l.$element.removeAttr("aria-describedby").trigger("hidden.bs."+l.type);e&&e()}var l=this,p=a(this.$tip),r=a.Event("hide.bs."+this.type);this.$element.trigger(r);if(!r.isDefaultPrevented())return p.removeClass("in"),a.support.transition&&p.hasClass("fade")?p.one("bsTransitionEnd",f).emulateTransitionEnd(c.TRANSITION_DURATION):f(),this.hoverState=null,this};c.prototype.fixTitle=function(){var e=this.$element;(e.attr("title")||
"string"!=typeof e.attr("data-original-title"))&&e.attr("data-original-title",e.attr("title")||"").attr("title","")};c.prototype.hasContent=function(){return this.getTitle()};c.prototype.getPosition=function(e){e=e||this.$element;var f=e[0],l="BODY"==f.tagName,p=f.getBoundingClientRect();null==p.width&&(p=a.extend({},p,{width:p.right-p.left,height:p.bottom-p.top}));f=window.SVGElement&&f instanceof window.SVGElement;f=l?{top:0,left:0}:f?null:e.offset();e={scroll:l?document.documentElement.scrollTop||
document.body.scrollTop:e.scrollTop()};l=l?{width:a(window).width(),height:a(window).height()}:null;return a.extend({},p,e,l,f)};c.prototype.getCalculatedOffset=function(e,f,l,p){return"bottom"==e?{top:f.top+f.height,left:f.left+f.width/2-l/2}:"top"==e?{top:f.top-p,left:f.left+f.width/2-l/2}:"left"==e?{top:f.top+f.height/2-p/2,left:f.left-l}:{top:f.top+f.height/2-p/2,left:f.left+f.width}};c.prototype.getViewportAdjustedDelta=function(e,f,l,p){var r={top:0,left:0};if(!this.$viewport)return r;var t=
this.options.viewport&&this.options.viewport.padding||0,q=this.getPosition(this.$viewport);/right|left/.test(e)?(l=f.top-t-q.scroll,f=f.top+t-q.scroll+p,l<q.top?r.top=q.top-l:f>q.top+q.height&&(r.top=q.top+q.height-f)):(p=f.left-t,f=f.left+t+l,p<q.left?r.left=q.left-p:f>q.right&&(r.left=q.left+q.width-f));return r};c.prototype.getTitle=function(){var e=this.$element,f=this.options;return e.attr("data-original-title")||("function"==typeof f.title?f.title.call(e[0]):f.title)};c.prototype.getUID=function(e){do e+=
~~(1E6*Math.random());while(document.getElementById(e));return e};c.prototype.tip=function(){if(!this.$tip&&(this.$tip=a(this.options.template),1!=this.$tip.length))throw Error(this.type+" `template` option must consist of exactly 1 top-level element!");return this.$tip};c.prototype.arrow=function(){return this.$arrow=this.$arrow||this.tip().find(".tooltip-arrow")};c.prototype.enable=function(){this.enabled=!0};c.prototype.disable=function(){this.enabled=!1};c.prototype.toggleEnabled=function(){this.enabled=
!this.enabled};c.prototype.toggle=function(e){var f=this;e&&(f=a(e.currentTarget).data("bs."+this.type),f||(f=new this.constructor(e.currentTarget,this.getDelegateOptions()),a(e.currentTarget).data("bs."+this.type,f)));e?(f.inState.click=!f.inState.click,f.isInStateTrue()?f.enter(f):f.leave(f)):f.tip().hasClass("in")?f.leave(f):f.enter(f)};c.prototype.destroy=function(){var e=this;clearTimeout(this.timeout);this.hide(function(){e.$element.off("."+e.type).removeData("bs."+e.type);e.$tip&&e.$tip.detach();
e.$tip=null;e.$arrow=null;e.$viewport=null;e.$element=null})};c.prototype.sanitizeHtml=function(e){return h(e,this.options.whiteList,this.options.sanitizeFn)};var k=a.fn.tooltip;a.fn.tooltip=function(e){return this.each(function(){var f=a(this),l=f.data("bs.tooltip"),p="object"==typeof e&&e;if(l||!/destroy|hide/.test(e))if(l||f.data("bs.tooltip",l=new c(this,p)),"string"==typeof e)l[e]()})};a.fn.tooltip.Constructor=c;a.fn.tooltip.noConflict=function(){a.fn.tooltip=k;return this}}(jQuery);
+function(a){var n=function(m,g){this.init("popover",m,g)};if(!a.fn.tooltip)throw Error("Popover requires tooltip.js");n.VERSION="3.4.1";n.DEFAULTS=a.extend({},a.fn.tooltip.Constructor.DEFAULTS,{placement:"right",trigger:"click",content:"",template:'<div class="popover" role="tooltip"><div class="arrow"></div><h3 class="popover-title"></h3><div class="popover-content"></div></div>'});n.prototype=a.extend({},a.fn.tooltip.Constructor.prototype);n.prototype.constructor=n;n.prototype.getDefaults=function(){return n.DEFAULTS};
n.prototype.setContent=function(){var m=this.tip(),g=this.getTitle(),b=this.getContent();if(this.options.html){var d=typeof b;this.options.sanitize&&(g=this.sanitizeHtml(g),"string"===d&&(b=this.sanitizeHtml(b)));m.find(".popover-title").html(g);m.find(".popover-content").children().detach().end()["string"===d?"html":"append"](b)}else m.find(".popover-title").text(g),m.find(".popover-content").children().detach().end().text(b);m.removeClass("fade top bottom left right in");m.find(".popover-title").html()||
m.find(".popover-title").hide()};n.prototype.hasContent=function(){return this.getTitle()||this.getContent()};n.prototype.getContent=function(){var m=this.$element,g=this.options;return m.attr("data-content")||("function"==typeof g.content?g.content.call(m[0]):g.content)};n.prototype.arrow=function(){return this.$arrow=this.$arrow||this.tip().find(".arrow")};var h=a.fn.popover;a.fn.popover=function(m){return this.each(function(){var g=a(this),b=g.data("bs.popover"),d="object"==typeof m&&m;if(b||!/destroy|hide/.test(m))if(b||
g.data("bs.popover",b=new n(this,d)),"string"==typeof m)b[m]()})};a.fn.popover.Constructor=n;a.fn.popover.noConflict=function(){a.fn.popover=h;return this}}(jQuery);
+function(a){function n(g,b){this.$body=a(document.body);this.$scrollElement=a(g).is(document.body)?a(window):a(g);this.options=a.extend({},n.DEFAULTS,b);this.selector=(this.options.target||"")+" .nav li > a";this.offsets=[];this.targets=[];this.activeTarget=null;this.scrollHeight=0;this.$scrollElement.on("scroll.bs.scrollspy",a.proxy(this.process,this));this.refresh();this.process()}function h(g){return this.each(function(){var b=a(this),d=b.data("bs.scrollspy"),c="object"==typeof g&&g;d||b.data("bs.scrollspy",
d=new n(this,c));if("string"==typeof g)d[g]()})}n.VERSION="3.4.1";n.DEFAULTS={offset:10};n.prototype.getScrollHeight=function(){return this.$scrollElement[0].scrollHeight||Math.max(this.$body[0].scrollHeight,document.documentElement.scrollHeight)};n.prototype.refresh=function(){var g=this,b="offset",d=0;this.offsets=[];this.targets=[];this.scrollHeight=this.getScrollHeight();a.isWindow(this.$scrollElement[0])||(b="position",d=this.$scrollElement.scrollTop());this.$body.find(this.selector).map(function(){var c=
a(this);c=c.data("target")||c.attr("href");var k=/^#./.test(c)&&a(c);return k&&k.length&&k.is(":visible")&&[[k[b]().top+d,c]]||null}).sort(function(c,k){return c[0]-k[0]}).each(function(){g.offsets.push(this[0]);g.targets.push(this[1])})};n.prototype.process=function(){var g=this.$scrollElement.scrollTop()+this.options.offset,b=this.getScrollHeight(),d=this.options.offset+b-this.$scrollElement.height(),c=this.offsets,k=this.targets,e=this.activeTarget,f;this.scrollHeight!=b&&this.refresh();if(g>=
d)return e!=(f=k[k.length-1])&&this.activate(f);if(e&&g<c[0])return this.activeTarget=null,this.clear();for(f=c.length;f--;)e!=k[f]&&g>=c[f]&&(void 0===c[f+1]||g<c[f+1])&&this.activate(k[f])};n.prototype.activate=function(g){this.activeTarget=g;this.clear();g=a(this.selector+'[data-target="'+g+'"],'+this.selector+'[href="'+g+'"]').parents("li").addClass("active");g.parent(".dropdown-menu").length&&(g=g.closest("li.dropdown").addClass("active"));g.trigger("activate.bs.scrollspy")};n.prototype.clear=
function(){a(this.selector).parentsUntil(this.options.target,".active").removeClass("active")};var m=a.fn.scrollspy;a.fn.scrollspy=h;a.fn.scrollspy.Constructor=n;a.fn.scrollspy.noConflict=function(){a.fn.scrollspy=m;return this};a(window).on("load.bs.scrollspy.data-api",function(){a('[data-spy="scroll"]').each(function(){var g=a(this);h.call(g,g.data())})})}(jQuery);
+function(a){function n(b){return this.each(function(){var d=a(this),c=d.data("bs.tab");c||d.data("bs.tab",c=new h(this));if("string"==typeof b)c[b]()})}var h=function(b){this.element=a(b)};h.VERSION="3.4.1";h.TRANSITION_DURATION=150;h.prototype.show=function(){var b=this.element,d=b.closest("ul:not(.dropdown-menu)"),c=b.data("target");c||(c=(c=b.attr("href"))&&c.replace(/.*(?=#[^\s]*$)/,""));if(!b.parent("li").hasClass("active")){var k=d.find(".active:last a"),e=a.Event("hide.bs.tab",{relatedTarget:b[0]}),
f=a.Event("show.bs.tab",{relatedTarget:k[0]});k.trigger(e);b.trigger(f);f.isDefaultPrevented()||e.isDefaultPrevented()||(c=a(document).find(c),this.activate(b.closest("li"),d),this.activate(c,c.parent(),function(){k.trigger({type:"hidden.bs.tab",relatedTarget:b[0]});b.trigger({type:"shown.bs.tab",relatedTarget:k[0]})}))}};h.prototype.activate=function(b,d,c){function k(){e.removeClass("active").find("> .dropdown-menu > .active").removeClass("active").end().find('[data-toggle="tab"]').attr("aria-expanded",
!1);b.addClass("active").find('[data-toggle="tab"]').attr("aria-expanded",!0);f?(b[0].offsetWidth,b.addClass("in")):b.removeClass("fade");b.parent(".dropdown-menu").length&&b.closest("li.dropdown").addClass("active").end().find('[data-toggle="tab"]').attr("aria-expanded",!0);c&&c()}var e=d.find("> .active"),f=c&&a.support.transition&&(e.length&&e.hasClass("fade")||!!d.find("> .fade").length);e.length&&f?e.one("bsTransitionEnd",k).emulateTransitionEnd(h.TRANSITION_DURATION):k();e.removeClass("in")};
var m=a.fn.tab;a.fn.tab=n;a.fn.tab.Constructor=h;a.fn.tab.noConflict=function(){a.fn.tab=m;return this};var g=function(b){b.preventDefault();n.call(a(this),"show")};a(document).on("click.bs.tab.data-api",'[data-toggle="tab"]',g).on("click.bs.tab.data-api",'[data-toggle="pill"]',g)}(jQuery);
+function(a){function n(g){return this.each(function(){var b=a(this),d=b.data("bs.affix"),c="object"==typeof g&&g;d||b.data("bs.affix",d=new h(this,c));if("string"==typeof g)d[g]()})}var h=function(g,b){this.options=a.extend({},h.DEFAULTS,b);this.$target=(this.options.target===h.DEFAULTS.target?a(this.options.target):a(document).find(this.options.target)).on("scroll.bs.affix.data-api",a.proxy(this.checkPosition,this)).on("click.bs.affix.data-api",a.proxy(this.checkPositionWithEventLoop,this));this.$element=
a(g);this.pinnedOffset=this.unpin=this.affixed=null;this.checkPosition()};h.VERSION="3.4.1";h.RESET="affix affix-top affix-bottom";h.DEFAULTS={offset:0,target:window};h.prototype.getState=function(g,b,d,c){var k=this.$target.scrollTop(),e=this.$element.offset(),f=this.$target.height();if(null!=d&&"top"==this.affixed)return k<d?"top":!1;if("bottom"==this.affixed)return null!=d?k+this.unpin<=e.top?!1:"bottom":k+f<=g-c?!1:"bottom";var l=null==this.affixed;e=l?k:e.top;return null!=d&&k<=d?"top":null!=
c&&e+(l?f:b)>=g-c?"bottom":!1};h.prototype.getPinnedOffset=function(){if(this.pinnedOffset)return this.pinnedOffset;this.$element.removeClass(h.RESET).addClass("affix");var g=this.$target.scrollTop();return this.pinnedOffset=this.$element.offset().top-g};h.prototype.checkPositionWithEventLoop=function(){setTimeout(a.proxy(this.checkPosition,this),1)};h.prototype.checkPosition=function(){if(this.$element.is(":visible")){var g=this.$element.height(),b=this.options.offset,d=b.top,c=b.bottom,k=Math.max(a(document).height(),
a(document.body).height());"object"!=typeof b&&(c=d=b);"function"==typeof d&&(d=b.top(this.$element));"function"==typeof c&&(c=b.bottom(this.$element));b=this.getState(k,g,d,c);if(this.affixed!=b){null!=this.unpin&&this.$element.css("top","");d="affix"+(b?"-"+b:"");var e=a.Event(d+".bs.affix");this.$element.trigger(e);if(e.isDefaultPrevented())return;this.affixed=b;this.unpin="bottom"==b?this.getPinnedOffset():null;this.$element.removeClass(h.RESET).addClass(d).trigger(d.replace("affix","affixed")+
".bs.affix")}"bottom"==b&&this.$element.offset({top:k-g-c})}};var m=a.fn.affix;a.fn.affix=n;a.fn.affix.Constructor=h;a.fn.affix.noConflict=function(){a.fn.affix=m;return this};a(window).on("load",function(){a('[data-spy="affix"]').each(function(){var g=a(this),b=g.data();b.offset=b.offset||{};null!=b.offsetBottom&&(b.offset.bottom=b.offsetBottom);null!=b.offsetTop&&(b.offset.top=b.offsetTop);n.call(g,b)})})}(jQuery);process=process||{env:{NODE_ENV:"development"}};